# Generated by Django 5.2.6 on 2026-05-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professional_title", models.CharField(blank=True, max_length=120)),
                ("display_name", models.CharField(blank=True, max_length=180)),
                ("professional_email", models.EmailField(blank=True, max_length=254)),
                ("professional_phone", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True)),
                ("clinical_interests", models.TextField(blank=True)),
                ("education", models.JSONField(blank=True, default=list)),
                ("career_details", models.JSONField(blank=True, default=list)),
                ("awards_certifications", models.JSONField(blank=True, default=list)),
                ("affiliations", models.JSONField(blank=True, default=list)),
                ("profile_completion", models.PositiveSmallIntegerField(default=0)),
                ("completed_sections", models.JSONField(blank=True, default=list)),
                (
                    "last_profile_reminder_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__first_name", "user__last_name", "user__username"),
            },
        ),
    ]
