# Generated by Django 5.2.6 on 2026-05-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_clinicianprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicianprofile",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="full_names",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="portfolio_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="telegram_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
