# Generated by Django 5.2.6 on 2026-05-25 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_clinicianprofile_facebook_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeEnrollmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_names", models.CharField(max_length=220)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("whatsapp_number", models.CharField(blank=True, max_length=50)),
                ("telegram_chat_id", models.CharField(blank=True, max_length=80)),
                ("telegram_username", models.CharField(blank=True, max_length=120)),
                ("requested_role", models.CharField(blank=True, max_length=80)),
                ("requested_team", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("internal", "Internal"),
                            ("api", "API"),
                        ],
                        default="api",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_employee_enrollment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="accounts_em_status_c92cf1_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="accounts_em_source_3d8c94_idx",
                    ),
                    models.Index(
                        fields=["telegram_chat_id", "status"],
                        name="accounts_em_telegra_2c6953_idx",
                    ),
                ],
            },
        ),
    ]
