# Generated by Django 5.2.6 on 2026-06-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_employeeenrollmentrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("clinician", "Clinician"),
                            ("receptionist", "Receptionist"),
                        ],
                        max_length=30,
                    ),
                ),
                ("module_key", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("role", "module_key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "module_key"),
                        name="unique_role_module_permission",
                    )
                ],
            },
        ),
    ]
