# Generated by Django 5.2.6 on 2026-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rolemodulepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=80, unique=True),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("smtp_host", models.CharField(blank=True, max_length=180)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                (
                    "encryption",
                    models.CharField(
                        choices=[
                            ("starttls", "STARTTLS"),
                            ("ssl", "SSL/TLS"),
                            ("none", "None"),
                        ],
                        default="starttls",
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=180)),
                ("password", models.CharField(blank=True, max_length=500)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=160)),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                ("reply_to_name", models.CharField(blank=True, max_length=160)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System email settings",
                "verbose_name_plural": "System email settings",
            },
        ),
        migrations.AddField(
            model_name="employeeenrollmentrequest",
            name="review_email_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employeeenrollmentrequest",
            name="review_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
