# Generated by Django 5.2.6 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_systememailsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systememailsettings",
            name="brevo_api_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="systememailsettings",
            name="provider",
            field=models.CharField(
                choices=[("brevo_api", "Brevo API"), ("smtp", "SMTP fallback")],
                default="brevo_api",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EmailDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_key", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[("brevo_api", "Brevo API"), ("smtp", "SMTP")],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("to", models.JSONField(blank=True, default=list)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="accounts_em_status_b1a66b_idx",
                    ),
                    models.Index(
                        fields=["template_key", "created_at"],
                        name="accounts_em_templat_dfcc4f_idx",
                    ),
                ],
            },
        ),
    ]
