# Generated by Django 5.2.6 on 2026-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_systememailsettings_brevo_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolemodulepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("clinician", "Clinician"),
                    ("receptionist", "Receptionist"),
                    ("supplier_contact", "Supplier Contact"),
                    ("supplier_manager", "Supplier Manager"),
                    ("partner_contact", "Partner Contact"),
                    ("partner_manager", "Partner Manager"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("clinician", "Clinician"),
                    ("receptionist", "Receptionist"),
                    ("supplier_contact", "Supplier Contact"),
                    ("supplier_manager", "Supplier Manager"),
                    ("partner_contact", "Partner Contact"),
                    ("partner_manager", "Partner Manager"),
                ],
                default="receptionist",
                max_length=30,
            ),
        ),
    ]
