# Generated by Django 5.2.6 on 2026-06-22 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usernotificationchannel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_identifier",
                    models.CharField(db_index=True, max_length=180),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Successful login"),
                            ("failure", "Failed login"),
                            ("blocked", "Blocked by login protection"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("keycloak", "Keycloak"),
                            ("local", "Local authentication"),
                            ("local_fallback", "Local fallback"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=80)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authentication_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["attempted_identifier", "outcome", "created_at"],
                        name="accounts_au_attempt_524e6f_idx",
                    ),
                    models.Index(
                        fields=["method", "created_at"],
                        name="accounts_au_method_33b7b3_idx",
                    ),
                ],
            },
        ),
    ]
