# Generated by Django 5.2.6 on 2026-05-16 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient_code",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("primary_phone", models.CharField(blank=True, max_length=50)),
                ("secondary_phone", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "full_name_display",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="prefer_not_to_say",
                        max_length=30,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=120)),
                ("town_or_locality", models.CharField(blank=True, max_length=120)),
                ("village", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(default="active", max_length=30)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PatientCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_code", models.CharField(max_length=80)),
                ("condition_label", models.CharField(max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("historical", "Historical"),
                            ("suspected", "Suspected"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="clinic.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("family_medical_history", models.TextField(blank=True)),
                ("past_medical_history", models.TextField(blank=True)),
                ("allopathic_medication", models.TextField(blank=True)),
                (
                    "hiv_status",
                    models.CharField(
                        choices=[
                            ("reactive", "Reactive"),
                            ("non_reactive", "Non-reactive"),
                            ("unknown", "Unknown"),
                            ("undisclosed", "Undisclosed"),
                        ],
                        default="undisclosed",
                        max_length=30,
                    ),
                ),
                ("other_important_information", models.TextField(blank=True)),
                ("children_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="clinic.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_patient_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("new_consultation", "New consultation"),
                            ("follow_up", "Follow up"),
                            ("review", "Review"),
                        ],
                        default="new_consultation",
                        max_length=40,
                    ),
                ),
                ("visit_date", models.DateField()),
                ("visit_time", models.TimeField(blank=True, null=True)),
                ("main_complaint", models.TextField()),
                ("initial_complaints", models.TextField(blank=True)),
                ("physical_examination", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("remedy", models.TextField(blank=True)),
                ("reason_for_remedy", models.TextField(blank=True)),
                ("dietary_recommendation", models.TextField(blank=True)),
                ("lifestyle_recommendation", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="clinic.patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-visit_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="FollowUpEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_consult_symptoms", models.TextField(blank=True)),
                ("dietary_changes", models.TextField(blank=True)),
                ("lifestyle_changes", models.TextField(blank=True)),
                ("exercise_notes", models.TextField(blank=True)),
                ("energy_notes", models.TextField(blank=True)),
                ("evaluation_notes", models.TextField(blank=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_evaluation",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bp_first_reading", models.CharField(blank=True, max_length=50)),
                ("bp_second_reading", models.CharField(blank=True, max_length=50)),
                ("pulse", models.PositiveIntegerField(blank=True, null=True)),
                ("resp_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "glucose_mmol_l",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "glucose_context",
                    models.CharField(
                        choices=[
                            ("fasting", "Fasting"),
                            ("after_meals", "After meals"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "medication_taken_status",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("not_taken", "Not taken"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=80)),
                ("change_summary", models.JSONField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="clinic_audi_entity__96473c_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["primary_phone"], name="clinic_pati_primary_df330a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["full_name_display"], name="clinic_pati_full_na_798f47_idx"
            ),
        ),
    ]
