# Generated by Django 5.2.6 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_patient_email_new_patient_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="next_of_kin_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_of_kin_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_of_kin_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_of_kin_relationship",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_of_kin_relationship_other",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
