# Generated by Django 5.2.6 on 2026-05-24 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_patient_next_of_kin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("new_consultation", "New consultation"),
                            ("follow_up", "Follow up"),
                            ("review", "Review"),
                        ],
                        default="new_consultation",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_visit", "In visit"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=30,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("reception", "Reception"),
                            ("tablet", "Tablet"),
                            ("api", "API"),
                        ],
                        default="reception",
                        max_length=30,
                    ),
                ),
                ("identifier_type", models.CharField(blank=True, max_length=40)),
                ("source_label", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="clinic_pati_status_af0d4f_idx",
                    ),
                    models.Index(
                        fields=["patient", "status"],
                        name="clinic_pati_patient_066c55_idx",
                    ),
                ],
            },
        ),
    ]
