# Generated by Django 5.2.6 on 2026-05-24 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_patientcheckin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="after_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="before_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="changed_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="FormDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("patient_registration", "Patient registration"),
                            ("visit_new_consultation", "New consultation"),
                            ("visit_follow_up", "Follow up"),
                            ("vitals_entry", "Vitals entry"),
                            ("medical_history_update", "Medical history update"),
                        ],
                        max_length=80,
                    ),
                ),
                ("current_stage", models.CharField(blank=True, max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "last_saved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_drafts",
                        to="clinic.patient",
                    ),
                ),
                (
                    "related_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_drafts",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_saved_at", "-updated_at"),
                "indexes": [
                    models.Index(
                        fields=["owner_user", "status", "last_saved_at"],
                        name="clinic_form_owner_u_0955e7_idx",
                    ),
                    models.Index(
                        fields=["form_type", "status"],
                        name="clinic_form_form_ty_7a4cb2_idx",
                    ),
                    models.Index(
                        fields=["draft_key"], name="clinic_form_draft_k_75d3f2_idx"
                    ),
                ],
            },
        ),
    ]
