# Generated by Django 5.2.6 on 2026-05-24 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_auditlog_after_data_auditlog_before_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vital",
            options={"ordering": ("-recorded_at", "-created_at")},
        ),
        migrations.AddField(
            model_name="vital",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_vitals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vital",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="clinic.visit",
            ),
        ),
        migrations.AddIndex(
            model_name="vital",
            index=models.Index(
                fields=["visit", "recorded_at"], name="clinic_vita_visit_i_f79b61_idx"
            ),
        ),
    ]
