# Generated by Django 5.2.6 on 2026-05-25 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_alter_vital_options_vital_recorded_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("queued", "Queued"),
                            ("checked_in", "Checked in"),
                            ("vitals_recorded", "Vitals recorded"),
                            ("waiting_clinician", "Waiting clinician"),
                            ("in_consultation", "In consultation"),
                            ("visit_recorded", "Visit recorded"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=40,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("walk_in_queue", "Walk-in queue"),
                            ("appointment_checkin", "Appointment check-in"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=40,
                    ),
                ),
                ("queue_number", models.PositiveIntegerField(blank=True, null=True)),
                ("appointment_matched", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "check_in",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journey",
                        to="clinic.patientcheckin",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patient_journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="clinic.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_patient_journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journeys",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("service_date", "queue_number", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="PatientJourneyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("queued", "Queued"),
                            ("checked_in", "Checked in"),
                            ("vitals_recorded", "Vitals recorded"),
                            ("waiting_clinician", "Waiting clinician"),
                            ("in_consultation", "In consultation"),
                            ("visit_recorded", "Visit recorded"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=40,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="clinic.patientjourney",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_journey_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="patientjourney",
            index=models.Index(
                fields=["patient", "service_date", "is_active"],
                name="clinic_pati_patient_c71c5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientjourney",
            index=models.Index(
                fields=["current_stage", "service_date"],
                name="clinic_pati_current_bffc39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientjourney",
            index=models.Index(
                fields=["flow_type", "service_date", "queue_number"],
                name="clinic_pati_flow_ty_945bb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientjourneyevent",
            index=models.Index(
                fields=["journey", "created_at"], name="clinic_pati_journey_3af7bb_idx"
            ),
        ),
    ]
