# Generated by Django 5.2.6 on 2026-05-25 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0010_patientjourney_patientjourneyevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("new_consultation", "New consultation"),
                            ("follow_up", "Follow up"),
                            ("review", "Review"),
                        ],
                        default="follow_up",
                        max_length=40,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("api", "API"),
                        ],
                        default="internal",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("checked_in", "Checked in"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No show"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_clinician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("appointment_date", "appointment_time", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="patientjourney",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journeys",
                to="clinic.appointment",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "status"],
                name="clinic_appo_appoint_e3a153_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="clinic_appo_patient_616a63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["assigned_clinician", "appointment_date"],
                name="clinic_appo_assigne_2ddf9e_idx",
            ),
        ),
    ]
