# Generated by Django 5.2.6 on 2026-05-26 18:54

import clinic.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0012_patient_public_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("consent_form", "Consent form"),
                            ("patient_upload", "Patient upload"),
                            ("report", "Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("pending_signature", "Pending signature"),
                            ("signed", "Signed"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="generated",
                        max_length=40,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to=clinic.models.patient_document_upload_path
                    ),
                ),
                ("verification_payload", models.JSONField(blank=True, default=dict)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RenameIndex(
            model_name="patient",
            new_name="clinic_pati_public__255eb6_idx",
            old_name="clinic_pati_public__3b8d94_idx",
        ),
        migrations.AddField(
            model_name="patient",
            name="consent_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending consent"),
                    ("generated", "Consent generated"),
                    ("signed", "Consent signed"),
                    ("verified", "Consent verified"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_patient_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="clinic.patient",
            ),
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_patient_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="patientdocument",
            index=models.Index(
                fields=["patient", "document_type", "status"],
                name="clinic_pati_patient_58772d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientdocument",
            index=models.Index(
                fields=["document_id"], name="clinic_pati_documen_5e9a0c_idx"
            ),
        ),
    ]
