# Generated by Django 5.2.6 on 2026-05-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0013_patientdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="main_complaint",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("main_complaint", models.TextField(blank=True)),
                ("physical_examination", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("remedy", models.TextField(blank=True)),
                ("reason_for_remedy", models.TextField(blank=True)),
                ("dietary_recommendation", models.TextField(blank=True)),
                ("lifestyle_recommendation", models.TextField(blank=True)),
                ("previous_consult_symptoms", models.TextField(blank=True)),
                ("dietary_changes", models.TextField(blank=True)),
                ("lifestyle_changes", models.TextField(blank=True)),
                ("exercise_notes", models.TextField(blank=True)),
                ("energy_notes", models.TextField(blank=True)),
                ("evaluation_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="clinic.case",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="clinic.patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="clinic_case_patient_6945c0_idx",
                    ),
                    models.Index(
                        fields=["visit"], name="clinic_case_visit_i_62a07a_idx"
                    ),
                ],
            },
        ),
    ]
