# Generated by Django 5.2.6 on 2026-05-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0015_migrate_visit_data_to_cases"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FollowUpEvaluation",
        ),
    ]
