# Generated by Django 5.2.6 on 2026-05-31 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0016_remove_followupevaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=220)),
                (
                    "thread_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("group", "Group"),
                            ("patient", "Patient"),
                            ("appointment", "Appointment"),
                            ("system", "System"),
                        ],
                        default="direct",
                        max_length=40,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("external_reference", models.CharField(blank=True, max_length=180)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="clinic.appointment",
                    ),
                ),
                (
                    "clinical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="clinic.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_message_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="clinic.patientdocument",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="clinic.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_message_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="MessageParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("member", "Member"),
                            ("observer", "Observer"),
                        ],
                        default="member",
                        max_length=30,
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_muted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="clinic.messagethread",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("handoff", "Handoff"),
                            ("external", "External"),
                        ],
                        default="user",
                        max_length=30,
                    ),
                ),
                (
                    "external_channel",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("api", "API"),
                        ],
                        default="internal",
                        max_length=30,
                    ),
                ),
                ("external_message_id", models.CharField(blank=True, max_length=180)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="clinic.messagethread",
                    ),
                ),
            ],
            options={
                "ordering": ("sent_at", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="MessageDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("api", "API"),
                        ],
                        default="internal",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="delivered",
                        max_length=30,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("provider", models.CharField(blank=True, max_length=80)),
                ("provider_message_id", models.CharField(blank=True, max_length=180)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="clinic.message",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["channel", "status", "created_at"],
                        name="clinic_mess_channel_6a5e8a_idx",
                    ),
                    models.Index(
                        fields=["message", "channel"],
                        name="clinic_mess_message_957478_idx",
                    ),
                    models.Index(
                        fields=["recipient_user", "status"],
                        name="clinic_mess_recipie_331ab8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["thread_type", "last_message_at"],
                name="clinic_mess_thread__ffa7e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["patient", "last_message_at"],
                name="clinic_mess_patient_abaf20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["appointment", "last_message_at"],
                name="clinic_mess_appoint_3b9637_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagethread",
            index=models.Index(
                fields=["created_by", "last_message_at"],
                name="clinic_mess_created_023438_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messageparticipant",
            index=models.Index(
                fields=["user", "last_read_at"], name="clinic_mess_user_id_4f6d72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageparticipant",
            index=models.Index(
                fields=["thread", "user"], name="clinic_mess_thread__dc8747_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messageparticipant",
            unique_together={("thread", "user")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "sent_at"], name="clinic_mess_thread__1e1cd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "sent_at"], name="clinic_mess_sender__571d1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["external_channel", "external_message_id"],
                name="clinic_mess_externa_9f5170_idx",
            ),
        ),
    ]
