# Generated by Django 5.2.6 on 2026-05-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0017_messagethread_messageparticipant_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitSymptomProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_symptom_problems",
                        to="clinic.visit",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_problems",
                        to="clinic.patient",
                    ),
                ),
                (
                    "resolved_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_symptom_problems",
                        to="clinic.visit",
                    ),
                ),
            ],
            options={
                "ordering": ("status", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="clinic_visi_patient_1b763d_idx",
                    ),
                    models.Index(
                        fields=["opened_visit"], name="clinic_visi_opened__e3e9bc_idx"
                    ),
                    models.Index(
                        fields=["resolved_visit"], name="clinic_visi_resolve_e4b708_idx"
                    ),
                ],
            },
        ),
    ]
