# Generated by Django 5.2.6 on 2026-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0018_visitsymptomproblem"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="alcohol_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="alcohol_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="patient",
            name="occupation",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="patient",
            name="smoking_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="smoking_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="patient",
            name="smoking_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="digestive_review",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="visit",
            name="follow_up_review",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="visit",
            name="general_review",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="visit",
            name="reproductive_review",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="visit",
            name="sleep_mental_review",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
