# Generated by Django 5.2.6 on 2026-06-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0020_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
