# Generated by Django 5.2.6 on 2026-06-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_vitals_patient_id(apps, schema_editor):
    Vital = apps.get_model("clinic", "Vital")
    # For every vital with an associated visit, copy the visit's patient_id to the direct patient relation
    for vital in Vital.objects.filter(visit__isnull=False).select_related("visit"):
        vital.patient_id = vital.visit.patient_id
        vital.save(update_fields=["patient"])


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0021_patient_deleted_at_patient_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vital",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="clinic.patient",
            ),
        ),
        migrations.RunPython(
            populate_vitals_patient_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="vital",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vitals",
                to="clinic.visit",
            ),
        ),
        migrations.AddIndex(
            model_name="vital",
            index=models.Index(
                fields=["patient", "recorded_at"], name="clinic_vita_patient_058344_idx"
            ),
        ),
    ]
