# Generated by Django 5.2.6 on 2026-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0022_vital_patient_alter_vital_visit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("pending_signature", "Pending signature"),
                    ("signed", "Signed"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("invalidated", "Invalidated"),
                ],
                default="generated",
                max_length=40,
            ),
        ),
    ]
