# Generated by Django 5.2.6 on 2026-06-06 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0023_alter_patientdocument_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("company_code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("medical_aid", "Medical Aid"),
                            ("affiliate", "Affiliate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("tax_number", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name_plural": "Partner Companies",
                "ordering": ["name"],
            },
        ),
    ]
