# Generated by Django 5.2.6 on 2026-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0024_partnercompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnercompany",
            name="account_holder",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="partnercompany",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fnb", "First National Bank (FNB)"),
                    ("standard_bank", "Standard Bank"),
                    ("nedbank", "Nedbank"),
                    ("eswatini_bank", "Eswatini Bank"),
                    ("eswatini_building_society", "Eswatini Building Society"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="partnercompany",
            name="branch_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="partnercompany",
            name="company_code",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
