# Generated by Django 5.2.6 on 2026-06-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0025_partnercompany_account_holder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="has_medical_aid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_aid_patients",
                to="clinic.partnercompany",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_id_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_membership_ownership",
            field=models.CharField(
                blank=True,
                choices=[("self", "Self"), ("other", "Other")],
                default="self",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_owner_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_owner_national_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_owner_relationship",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
