# Generated by Django 5.2.6 on 2026-06-09 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0026_patient_has_medical_aid_patient_medical_aid_company_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZulipOutboundEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(max_length=80)),
                ("topic", models.CharField(max_length=255)),
                (
                    "linked_entity_type",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("ticket", "Support Ticket"),
                            ("appointment", "Appointment"),
                            ("consent", "Consent Form"),
                            ("employee", "Employee / Staff"),
                        ],
                        max_length=40,
                    ),
                ),
                ("linked_entity_id", models.CharField(max_length=100)),
                ("raw_payload", models.TextField()),
                ("sanitized_payload", models.TextField()),
                (
                    "template_key",
                    models.CharField(
                        blank=True, default="generic_update", max_length=80
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending delivery"),
                            ("success", "Delivered successfully"),
                            ("failed", "Delivery failed"),
                            ("retry_buffered", "Buffered for retry"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zulip_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="clinic_zuli_status_71d4ff_idx",
                    ),
                    models.Index(
                        fields=["channel", "topic"],
                        name="clinic_zuli_channel_85cf5c_idx",
                    ),
                    models.Index(
                        fields=["linked_entity_type", "linked_entity_id"],
                        name="clinic_zuli_linked__58fb2e_idx",
                    ),
                ],
            },
        ),
    ]
