# Generated by Django 5.2.6 on 2026-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0028_appointmenttype_blockedslot_externalsyncrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="notification_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="notification_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="preferred_notification_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="patient",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
