import { UserRoundCog } from "lucide-react";

import { AppShell } from "@/components/app-shell";
import { CreateLoginAccountForm } from "@/components/create-login-account-form";

export default async function EnrolUserPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const params = await searchParams;

  return (
    <AppShell title="Create login account">
      {params.error === "create_failed" && (
        <div className="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">
          Failed to enrol user. Check the details and try again.
        </div>
      )}

      <section className="grid gap-6 lg:grid-cols-[1fr_380px]">
        <div className="hh-panel p-5">
          <div className="mb-5 flex items-center gap-3">
            <UserRoundCog className="text-[var(--hh-purple)]" size={22} />
            <div>
              <h2 className="font-bold">Create login account</h2>
              <p className="mt-1 text-sm text-[#66736d]">Create Harmony MIS access. The system will generate the correct User ID for the selected account type.</p>
            </div>
          </div>

          <CreateLoginAccountForm />
        </div>

        <div className="hh-panel p-5">
          <h3 className="font-bold">Identity direction</h3>
          <p className="mt-2 text-sm leading-6 text-[#66736d]">
            User IDs are generated by the backend so they stay consistent across MIS and Keycloak. Employees use `HH200`, suppliers use `HH300`, and external partners use `HH400`.
          </p>
        </div>
      </section>
    </AppShell>
  );
}
